services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./examples:/examples:ro
    healthcheck:
      test: ["CMD", "bash", "-lc", "wget -qO- http://localhost:8123/ping | grep -q Ok"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  clickhouse_data:

